---
"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:

  nuitka-issue-3173:
    name: "Nuitka: test for #3173"
    runs-on: windows-2022
    steps:
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install "uv == 0.4.28"
      - name: Install Nuitka
        run: |
          uv --no-progress venv
          uv --no-progress pip install "nuitka == 2.4.11" "ordered-set == 4.1.0" "zstandard == 0.23.0"
      - name: List uv CLIs
        continue-on-error: true
        run: |
          uv run
      - name: Nuitka --version - Working case
        run: |
          uv --no-progress run --frozen -- python -m nuitka --version
      - name: Nuitka --version - Broken case
        run: |
          uv --no-progress run --frozen -- nuitka --version
