---
"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:

  nuitka-issue-3173:
    name: "Nuitka: test for #3173"
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - "macos-15"  # arm64
          - "macos-13"  # x86-64
          - "windows-2022"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install "uv == 0.5.26"
      - name: Install Nuitka
        run: |
          uv --no-progress venv
          uv --no-progress pip install "nuitka == 2.6.2"
      - name: List uv CLIs
        continue-on-error: true
        run: |
          uv run

      - name: uv run python --module nuitka - Works on all platforms
        run: |
          uv --no-progress run --frozen -- python --module nuitka --version

      - name: uv run --module nuitka
        run: |
          uv --no-progress run --frozen --module -- nuitka --version

      - name: uv run nuitka - Broken on Windows
        if: runner.os != 'Windows'
        run: |
          uv --no-progress run --frozen -- nuitka --version

      - name: uv run nuitka.cmd - Only works on Windows
        run: |
          uv --no-progress run --frozen -- nuitka.cmd --version